local words = {
    "clouds_rainbow_rattle", "banana_rattle", "llama_rattle", "golden_maned_unicorn_rattle", 
    "camping_2023_log_bench", "camping_2023_camping_tent", "camping_2023_flashlight", 
    "camping_2023_sleeping_bag", "camping_2023_guitar", "camping_2023_sparkler", 
    "camping_2023_bongos", "capuchin_2024_handcuffs", "capuchin_2024_compass", 
    "capuchin_2024_whip_grappling_hook", "capuchin_2024_fire_ring_propeller", 
    "capuchin_2024_tophat_flying_disc", "capuchin_2024_peanut_balloon", 
    "capuchin_2024_seal_pogo", "capuchin_2024_peanut_friend_chew_toy", 
    "desert_2022_cactus_friend_plushie", "desert_2022_anhk_pogostick", 
    "desert_2022_scarab_grapple", "desert_2022_desert_drum", "desert_2022_cactus_balloon", 
    "desert_2022_crook_throw_toy", "easter_2022_carrot_friend_plushie", 
    "easter_2022_spring_bunny_leash", "easter_2022_carrot_pogo_stick", 
    "easter_2024_easter_chick_rattle", "easter_2024_classic_trade_stand", 
    "easter_2024_carrot_bushel_chew_toy", "easter_2024_lamb_carrot_plushie", 
    "fall_2022_corn_grapple", "fall_2022_mushroom_pogo", "fall_2022_finger_piano", 
    "fall_2022_acorn_plushie", "fall_2022_cinnamon_stick", "fall_2022_rain_cloud_balloon", 
    "fire_dimension_2024_flame_sword", "fossil_2024_dimorphodon_fossil", 
    "fossil_2024_brachiosaurus_fossil", "fossil_2024_elasmosaurus_fossil", 
    "fossil_2024_velociraptor_fossil", "fossil_2024_ankylosaurus_fossil", 
    "gifthat_2023_celestial_balloon", "gifthat_2023_bumblebee_grappling_hook", 
    "gifthat_2023_pancake_throwing_disc", "gifthat_2023_harp_grappling_hook", 
    "gifthat_2023_bumblebee_pogo_stick", "gifthat_2023_love_envelope_balloon", 
    "gifthat_2023_succulent_plush", "gifthat_2023_leek_chew_toy", 
    "gifthat_2023_celestial_propeller", "gifthat_2023_mermaid_rattle", 
    "gifthat_may_2024_dice_throw_toy", "gifthat_may_2024_paper_towel_chew_toy", 
    "gifthat_may_2024_paintbrush_leash", "gifthat_may_2024_fan_propeller", 
    "gifthat_may_2024_tree_plush", "gifthat_may_2024_flying_clock", 
    "gifthat_may_2024_saturn_balloon", "gifthat_may_2024_disco_ball_balloon", 
    "gifthat_may_2024_viking_shield_throw_toy", "gifthat_may_2024_flip_phone_toy", 
    "gifthat_may_2024_rainbow_leash", "gifthat_may_2024_wallet_chew_toy", 
    "gifthat_may_2024_chattering_teeth_grappling_hook", 
    "gifthat_may_2024_filipino_fan_throw_toy", "gifthat_may_2024_wooden_spoon_toy", 
    "gifthat_may_2024_recycled_banjo", "gifthat_may_2024_baseball_throw_toy", 
    "gifthat_may_2024_pizza_throwing_disc", "gifthat_may_2024_hairbrush_chew_toy", 
    "gift_refresh_2022_anchor_balloon", "gift_refresh_2022_clover_balloon", 
    "gift_refresh_2022_fairy_light_rattle", "gift_refresh_2022_angelic_grappling_hook", 
    "gift_refresh_2022_eclipse_flying_disc", "gift_refresh_2022_flower_mirror_chew_toy", 
    "gift_refresh_2022_mushroom_plushie", "gift_refresh_2022_orchid_propeller", 
    "gift_refresh_2022_bat_key_pogostick", "gift_refresh_2022_water_soaker_grappling_hook", 
    "gift_refresh_2022_bouncy_ball_pogo", "gift_refresh_2022_futuristic_turbine_propeller", 
    "gift_refresh_2022_anvil_balloon", "gift_refresh_2022_chainsaw_rattle", 
    "gift_refresh_2022_paper_plane_launcher_grappling_hook", 
    "gift_refresh_2022_cd_throwing_disc", "gift_refresh_2022_fishing_tackle_grappling_hook", 
    "gift_refresh_2022_hang_glider_balloon", "gift_refresh_2022_robo_plush_3000", 
    "gift_refresh_2022_meaty_chew_toy", "gifthat_refresh_2023_olympian_rattle", 
    "gifthat_refresh_2023_robo_balloon", "gifthat_refresh_2023_water_drop_plush", 
    "gifthat_refresh_2023_magic_staff_light", "gifthat_refresh_2023_winged_flying_disc", 
    "gifthat_refresh_2023_natures_crossbow", "gifthat_refresh_2023_witch_propeller", 
    "gifthat_refresh_2023_ice_pogo_stick", "gifthat_refresh_2023_robo_plush", 
    "gifthat_refresh_2023_ray_gun_leash", "gifthat_refresh_2023_love_perfume", 
    "gifthat_refresh_2023_magic_scroll_chew_toy", "galaxy_flying_disc", 
    "daisy_flying_disc", "venus_fly_trap_rattle", "rose_pogo", 
    "magical_princess_chew_toy", "cactus_plushie_chew_toy", "satellite_balloon", 
    "pink_cat_balloon", "rocket_grappling_hook", "magical_princess_leash", 
    "cactus_grappling_hook", "galaxy_propeller", "gorilla_fair_2023_banana_leaf_balloon", 
    "gorilla_fair_2023_chef_item", "gorilla_fair_2023_banana_tree_pogo", 
    "gorilla_fair_2023_astronaut_item", "gorilla_fair_2023_carousel_propeller", 
    "gorilla_fair_2023_fairground_pogo", "gorilla_fair_2023_tom_tom_drum_flying_disc", 
    "gorilla_fair_2023_banana_chew_toy", "gorilla_fair_2023_emperor_item", 
    "gorilla_fair_2023_karate_item", "halloween_2021_pumpkin_voodoo_doll", 
    "halloween_2021_pumpkin_balloon", "halloween_2021_pumpkin_flying_disc", 
    "halloween_2021_victorian_candle_rattle", "halloween_2021_bat_propeller", 
    "halloween_2021_ghost_balloon", "halloween_2021_scythe_grapple", 
    "halloween_2022_bat_wings_balloon", "halloween_2022_pumpkin_basket_plushie", 
    "halloween_2022_spider_web_disc", "halloween_2022_potion_bottle_balloon", 
    "halloween_2022_skull_propeller", "halloween_2022_zombie_finger_rattle", 
    "halloween_2022_vampire_grappling_hook", "halloween_2023_pumpkin_kitty_plushie", 
    "halloween_2023_full_moon_flying_disc", "halloween_2023_vampire_chew_toy", 
    "halloween_2023_jack_o_lantern_light", "halloween_2023_vampire_skull_rattle", 
    "halloween_2023_spellbook_throw_toy", "halloween_2023_candy_skewer", 
    "halloween_2023_bandage_propeller", "halloween_2024_netzooka", 
    "halloween_2024_bear_head_plush", "halloween_2024_raven_flying_disc", 
    "halloween_2024_trick_or_treat_pouch", "halloween_2024_pumpkin_candle", 
    "halloween_2024_zombie_flying_disc", "halloween_2024_demon_fox_chew_toy", 
    "halloween_2024_vampire_rattle", "halloween_2024_butterfly_leash", 
    "halloween_2024_skeleton_rattle", "halloween_2024_haunted_tombstone_grappling_hook", 
    "halloween_2024_witch_hat_chew_toy", "halloween_2024_pumpkin_nightmare_grappling_hook", 
    "halloween_2024_pumpkin_head_rattle", "halloween_2024_candied_apples_grappling_hook", 
    "halloween_2024_fallen_stars_flying_disc", "halloween_2024_pumpkin_stick_rattle", 
    "halloween_2024_vampire_bats_grappling_hook", "halloween_2024_bone_leash", 
    "halloween_2024_golden_axe_chew_toy", "halloween_2024_skeleton_flying_disc", 
    "halloween_2024_witch_broom_rattle", "halloween_2024_mummy_flying_disc", 
    "halloween_2024_fallen_stars_balloon", "halloween_2024_mummy_leash", 
    "halloween_2024_candy_corn_chew_toy", "halloween_2024_zombie_head_grappling_hook", 
    "halloween_2024_pumpkin_reaper_chew_toy", "halloween_2024_ghost_grappling_hook", 
    "halloween_2024_witch_flying_disc", "halloween_2024_haunted_cauldron_chew_toy", 
    "halloween_2024_pumpkin_flying_disc", "halloween_2024_skeleton_head_chew_toy", 
    "halloween_2024_zombie_brains_rattle", "halloween_2024_zombie_hand_grappling_hook", 
    "halloween_2024_bear_head_flying_disc", "halloween_2024_skeleton_hands_leash", 
    "halloween_2024_raven_rattle", "halloween_2024_zombie_pumpkin_leash", 
    "halloween_2024_skeleton_hand_flying_disc", "halloween_2024_haunted_flying_disc", 
    "halloween_2024_mummy_grappling_hook", "halloween_2024_pumpkin_face_grappling_hook", 
    "halloween_2024_bear_flying_disc", "halloween_2024_hanging_skull_rattle", 
    "halloween_2024_pumpkin_goblins_grappling_hook", "halloween_2024_mummy_hands_flying_disc", 
    "halloween_2024_skeleton_flying_disc", "halloween_2024_goblin_skeleton_rattle", 
    "halloween_2024_bone_flying_disc", "halloween_2024_pumpkin_kittens_grappling_hook", 
    "halloween_2024_giant_pumpkin_flying_disc", "halloween_2024_candy_basket_rattle", 
    "halloween_2024_pumpkin_caterpillar_chew_toy", "halloween_2024_witch_flying_disc", 
    "halloween_2024_candy_bat_grappling_hook", "halloween_2024_zombie_mummy_grappling_hook", 
    "halloween_2024_candy_bat_rattle", "halloween_2024_mummy_candy_grappling_hook", 
    "halloween_2024_skeleton_zombie_chew_toy", "halloween_2024_pumpkin_zombie_leash", 
    "halloween_2024_mummy_witch_rattle", "halloween_2024_skeleton_pumpkin_chew_toy", 
    "halloween_2024_zombie_witch_flying_disc", "halloween_2024_bear_zombie_rattle", 
    "halloween_2024_pumpkin_cat_flying_disc", "halloween_2024_witch_bear_flying_disc", 
    "halloween_2024_zombie_frog_rattle", "halloween_2024_zombie_owl_flying_disc", 
    "halloween_2024_bear_frog_rattle", "halloween_2024_skeleton_owl_flying_disc", 
    "halloween_2024_pumpkin_frog_rattle", "halloween_2024_zombie_frog_flying_disc", 
    "halloween_2024_pumpkin_frog_flying_disc", "halloween_2024_zombie_owl_rattle", 
    "halloween_2024_witch_owl_flying_disc", "halloween_2024_bear_owl_rattle", 
    "halloween_2024_zombie_ghost_flying_disc", "halloween_2024_mummy_ghost_flying_disc", 
    "halloween_2024_pumpkin_ghost_rattle", "halloween_2024_owl_bear_flying_disc", 
    "halloween_2024_frog_bear_rattle", "halloween_2024_ghost_frog_flying_disc", 
    "halloween_2024_pumpkin_frog_flying_disc", "halloween_2024_owl_frog_rattle", 
    "halloween_2024_ghost_frog_rattle", "halloween_2024_frog_zombie_rattle", 
    "halloween_2024_owl_zombie_flying_disc", "halloween_2024_zombie_ghost_rattle", 
    "halloween_2024_frog_ghost_flying_disc", "halloween_2024_zombie_frog_flying_disc", 
    "halloween_2024_bear_frog_flying_disc", "halloween_2024_frog_bear_flying_disc", 
    "halloween_2024_owl_bear_rattle", "halloween_2024_zombie_bear_flying_disc", 
    "halloween_2024_bear_zombie_flying_disc", "halloween_2024_frog_bear_flying_disc", 
    "halloween_2024_bear_frog_flying_disc", "halloween_2024_zombie_frog_bear_flying_disc", 
    "halloween_2024_bear_frog_bear_flying_disc", "halloween_2024_ghost_bear_rattle", 
    "halloween_2024_frog_bear_ghost_flying_disc", "halloween_2024_bear_ghost_flying_disc", 
    "halloween_2024_ghost_zombie_flying_disc", "halloween_2024_ghost_frog_bear_flying_disc", 
    "halloween_2024_zombie_bear_frog_flying_disc", "halloween_2024_ghost_frog_zombie_flying_disc", 
    "halloween_2024_ghost_frog_bear_zombie_flying_disc", "halloween_2024_bear_ghost_frog_zombie_flying_disc", 
    "halloween_2024_frog_bear_ghost_zombie_flying_disc", "halloween_2024_bear_zombie_ghost_flying_disc", 
    "halloween_2024_ghost_zombie_bear_flying_disc", "halloween_2024_frog_zombie_ghost_bear_flying_disc"
}

local function replaceToy(word)
    local originalCode = "print(\"This is a toy\")"  -- Replace this with your actual code
    local newCode = originalCode:gsub("toy", word)
    load(newCode)()
end

for _, word in ipairs(words) do
    replaceToy(word)
    os.execute("sleep 0.5")  -- Pause for 0.5 seconds
end
